pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-u root --privileged -v /root/.m2:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock -v /bin/docker:/bin/docker'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod 755 ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh'
                sh 'docker build jenkins'
            }
        }
    }
}
